import { useEffect, useState } from "react";
import { useAdminStore } from "../../store/useAdminStore";
import { Search, FileText, Loader2, Download } from "lucide-react";

const AdminReports = () => {
  const { reports, fetchReports, isLoadingReports } = useAdminStore();
  const [searchTerm, setSearchTerm] = useState("");

  useEffect(() => {
    fetchReports();
  }, [fetchReports]);

  const filteredReports = reports.filter(r => 
    r.title?.toLowerCase().includes(searchTerm.toLowerCase()) || 
    r.patientId?.fullName?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8 pb-16">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Hospital Reports</h1>
          <p className="text-sm text-slate-500 mt-1">Access and manage all generated medical reports.</p>
        </div>
      </div>

      <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="p-6 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <div className="relative">
            <Search className="w-4 h-4 absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400" />
            <input 
              type="text" 
              placeholder="Search reports or patients..." 
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-sm w-full sm:w-64 focus:outline-none focus:border-[#698bf4]" 
            />
          </div>
        </div>

        <div className="overflow-x-auto">
          {isLoadingReports ? (
            <div className="flex justify-center p-12"><Loader2 className="w-8 h-8 animate-spin text-[#698bf4]" /></div>
          ) : (
            <table className="w-full text-sm text-left">
              <thead className="text-xs text-slate-500 uppercase bg-slate-50 border-b border-slate-100">
                <tr>
                  <th className="px-6 py-4 font-semibold">Report Title</th>
                  <th className="px-6 py-4 font-semibold">Patient</th>
                  <th className="px-6 py-4 font-semibold">Generated By</th>
                  <th className="px-6 py-4 font-semibold">Date</th>
                  <th className="px-6 py-4 font-semibold text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredReports.length === 0 ? (
                  <tr>
                    <td colSpan="5" className="px-6 py-8 text-center text-slate-500">No reports found matching your criteria.</td>
                  </tr>
                ) : (
                  filteredReports.map((r) => (
                    <tr key={r._id} className="hover:bg-slate-50/50 transition-colors">
                      <td className="px-6 py-4 flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-indigo-50 flex-shrink-0 flex items-center justify-center text-[#698bf4]">
                          <FileText className="w-4 h-4" />
                        </div>
                        <p className="font-medium text-slate-800">{r.title}</p>
                      </td>
                      <td className="px-6 py-4 text-slate-600">{r.patientId?.fullName || "Unknown"}</td>
                      <td className="px-6 py-4 text-slate-600">Dr. {r.doctorId?.fullName || "Unknown"}</td>
                      <td className="px-6 py-4 text-slate-500 text-xs">
                        {new Date(r.createdAt).toLocaleDateString()}
                      </td>
                      <td className="px-6 py-4 text-right">
                        {r.fileUrl && (
                          <a 
                            href={r.fileUrl} 
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="inline-flex p-2 text-[#698bf4] hover:bg-indigo-50 rounded-lg transition-colors title='Download'"
                          >
                            <Download className="w-4 h-4" />
                          </a>
                        )}
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
};

export default AdminReports;
